# Generated by Django 3.2.12 on 2022-02-03 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('estacion_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='lineas.estacion')),
                ('estacion_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='lineas.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=255)),
                ('viajes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='lineas.viajes')),
            ],
        ),
    ]
