# Generated by Django 3.2.12 on 2022-02-03 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0002_usuario_viajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='viajes',
        ),
        migrations.AddField(
            model_name='viajes',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='lineas.usuario'),
            preserve_default=False,
        ),
    ]
